### ISSUE TITLE
cmake创建vs工程无法调试

### ISSUE THREAD

**Issue by siten** [xiaoweime/WProtect#2]
你好：
下载原代码后创建vs工程后可以正常编译通过，但是调试WProtect.exe的时候vs显示找不到符号，断点也不会命中。
这个无法调试的原因是如何造成的，希望给个思路是哪里的问题，非常感谢！

**Comment by xiaoweime** [comment]
可以尝试修改为RelWithDebinfo编译选项

**Comment by orzIruo** [comment]
- -居然搜到了这个。虽说过去久远。你可以看下工程属性，优化要禁用，代码生成运行库要改下。常规里我把调试信息格式改成了-用于“编辑并继续”的程序数据库。然后可以断下来调试了。小伙伴们可以参考下。反正自己设置一下应该就可以了。

至于用cmake生成vs代码编译不过去的，后来发现是utf8编码问题，改成ascii码就编译成功了。

给后面的小伙伴作参考。

**Comment by progmboy** [comment]
不能调试的原因是cmake中有地方写的没兼容msvc.
去掉
SET(CMAKE_CXX_FLAGS_DEBUG "$ENV{CXXFLAGS} -O0 -Wall -g -ggdb ")#就是这两行东东
SET(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O3 -Wall")#
这两行就好了，因为在第一行的时候也就是Debug的时候给-O0了

**Comment by mzhongyy** [comment]
> 
老哥全靠你，搜了两天，你一分钟给我解决了

**Comment by mzhongyy** [comment]
> 不能调试的原因是cmake中有地方写的没兼容msvc. 去掉 SET(CMAKE_CXX_FLAGS_DEBUG "$ENV{CXXFLAGS} -O0 -Wall -g -ggdb ")#就是这两行东东 SET(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O3 -Wall")# 这两行就好了，因为在第一行的时候也就是Debug的时候给-O0了

老哥全靠你了，搜了两天头大了，你一分钟给我解决了
